name: "PHPUnit"

on:
  push:
    branches:
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  unit_tests:
    name: "Unit and functional tests"
    strategy:
      #fail-fast: false
      matrix:
        php-version:
          - "5.6"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"

      - name: "Execute unit tests"
        run: "vendor/bin/phpunit --testdox"